f_name=input("what is your name ")
print("my fist  name is :",f_name)
s_name=input("what is your name ")
print("my second  name is :",s_name)
#convert string into integers
f_num = input("Enter first number")
s_num = input("Enter second number")
sum_num = int(f_num) + int(s_num)
print("the sum of the numbers is :",sum_num)
diff_num = int(f_num) - int(s_num)
print("the difference of the numbers is :",diff_num)
